service: flex
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT api:app
runtime_config:
  python_version: 3
beta_settings:
  cloud_sql_instances: "thesis-lock:europe-west1:thesis-lock"
manual_scaling:
  instances: 1
env_variables:
  DEBUG: false